spring:
  application:
    name: financial-system
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mapping: false
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/financial
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: c3ByaW5nLWJvb3QtZGl2aWRlbmQtcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"
